[package]
name = "mpesa"
version = "0.4.2"
authors = ["Collins Muriuki <murerwacollins@gmail.com>"]
edition = "2018"
description = "A wrapper around the M-PESA API in Rust."
keywords = ["api", "mpesa", "mobile"]
repository = "https://github.com/collinsmuriuki/mpesa-rust"
readme = "./README.md"
license = "MIT"

[dependencies]
serde_json = "1.0"
serde_repr = "0.1"
openssl = {version = "0.10", optional = true}
base64 = {version = "0.13", optional = true}
failure = "0.1"
failure_derive = "0.1"
chrono = {version = "0.4", optional = true}

[dependencies.reqwest]
version = "0.11"
features = ["blocking", "json"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dev-dependencies]
dotenv = "0.15"

[features]
default = ["b2b", "b2c" ,"account_balance", "c2b_register", "c2b_simulate", "express_request"]
b2b = ["dep:openssl", "dep:base64"]
b2c = ["dep:openssl", "dep:base64"]
account_balance = ["dep:openssl", "dep:base64"]
c2b_register = []
c2b_simulate = []
express_request = ["dep:chrono", "dep:base64"]