[package]
name = "mpesa"
version = "0.0.1"
authors = ["Collins Muriuki <murerwacollins@gmail.com>"]
edition = "2018"
description = "A wrapper around the M-PESA API in Rust."
repository = "https://github.com/collinsmuriuki/mpesa-rust"
readme = "README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde = "1.0.114"
serde_json = "1.0"
dotenv = "0.15.0"
base64 = "0.12.3"
openssl = "0.10.30"