[package]
name = "mpesa"
version = "0.3.3"
authors = ["Collins Muriuki <murerwacollins@gmail.com>"]
edition = "2018"
description = "A wrapper around the M-PESA API in Rust."
keywords = ["api", "mpesa", "mobile"]
repository = "https://github.com/collinsmuriuki/mpesa-rust"
readme = "README.md"
license = "MIT"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[workspace]
members = ["mpesa_derive"]

[dependencies]
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15.0"
base64 = "0.12.3"
openssl = "0.10.30"
mpesa_derive = "0.2.1"
failure = "0.1.5"
failure_derive = "0.1.5"
chrono = "0.4"