name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - name: Build
      run: cargo build --verbose

  test:

    runs-on: ubuntu-latest

    steps:
    - name: Run tests
      env:
          CLIENT_KEY: ${{ secrets.CLIENT_KEY }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          INIT_PASSWORD: ${{ secrets.INIT_PASSWORD }}
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - uses: actions-rs/cargo@v1
      with:
          command: test
          args: --verbose --no-fail-fast
        
