name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - name: Build
      run: cargo build --verbose

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - name: Run Tests
      run: |
        export CLIENT_KEY=${{ secrets.CLIENT_KEY }}
        export CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
        export INIT_PASSWORD=${{ secrets.INIT_PASSWORD }}
        cargo test --verbose --no-fail-fast
        
